interface EdqConfigObject {
	EMAIL_VALIDATE_AUTH_TOKEN: string,
	EMAIL_TIMEOUT: string,
	EMAIL_ELEMENTS: Array<Element>,
	
	GLOBAL_INTUITIVE_AUTH_TOKEN: string,
	GLOBAL_INTUITIVE_ISO3_COUNTRY: string,
	GLOBAL_INTUITIVE_DATASET?: string,
	GLOBAL_INTUITIVE_ELEMENT: HTMLInputElement,
	GLOBAL_INTUITIVE_MAPPING: Array<any>,
	GLOBAL_INTUITIVE_USE_CURRENT_LOCATION: boolean,
	AUTOCOMPLETION_SETTINGS: object,
	GLOBAL_INTUITIVE_AFTER_FORMAT_CHANGE:any,
	
	GLOBAL_PHONE_VALIDATE_AUTH_TOKEN: string,
	PHONE_TIMEOUT: string,
	REVERSE_PHONE_APPEND_MAPPINGS?: Array<Element>,
	PHONE_ELEMENTS: Array<Element>,
	
	PRO_WEB_TIMEOUT: string,
	PRO_WEB_AUTH_TOKEN: string,
	PRO_WEB_SUBMIT_TRIGGERS: Array<any>,
	PRO_WEB_LAYOUT: string,
	PRO_WEB_COUNTRY: string,
	PRO_WEB_CALLBACK: string,
	PRO_WEB_MAPPING: Array<any>,
	VERIFICATION_MODAL_OVERRIDES: object,
}